# --- SERVICE ---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: prowlarr.torquasmvo.internal
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.214  # Reserve a free MetalLB IP
  selector:
    app: prowlarr
  ports:
    - name: http
      protocol: TCP
      port: 9696
      targetPort: 9696
