# kubernetes/apps/default/sabnzbd/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: default
  labels:
    app: sabnzbd
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sabnzbd.torquasmvo.internal
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.227
  selector:
    app: sabnzbd
  ports:
    - name: http
      port: 8080
      targetPort: 8080
