apiVersion: v1
kind: ServiceAccount
metadata:
  name: portainer-tailscale
  namespace: portainer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portainer-tailscale-clusteradmin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: portainer-tailscale
    namespace: portainer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: portainer-tailscale-role
  namespace: portainer
rules:
  # Allow creating secrets (cannot be restricted by name in RBAC)
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  # Let tailscaled store/read its state in Secret "portainer-tailscale-state"
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["portainer-tailscale-state"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: portainer-tailscale-rb
  namespace: portainer
subjects:
  - kind: ServiceAccount
    name: portainer-tailscale
    namespace: portainer
roleRef:
  kind: Role
  name: portainer-tailscale-role
  apiGroup: rbac.authorization.k8s.io
