apiVersion: v1
kind: Service
metadata:
  name: minecraft-creative
  annotations:
    external-dns.alpha.kubernetes.io/hostname: minecraft-creative.torquasmvo.internal
spec:
  type: LoadBalancer
  loadBalancerIP: "10.0.0.212" # Add this line
  ports:
    - name: creative-tcp
      port: 25565
      protocol: TCP
      targetPort: 25565
    - name: creative-udp
      port: 25565
      protocol: UDP
      targetPort: 25565
  selector:
    app.kubernetes.io/name: minecraft-creative
