# kubernetes/infrastructure/longhorn/ui/longhorn-ui-lb.yaml
apiVersion: v1
kind: Service
metadata:
  name: longhorn-ui-lb
  namespace: longhorn-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: longhorn.torquasmvo.internal
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.215 # A free IP from your MetalLB pool
  selector:
    app: longhorn-ui
  ports:
    - name: http
      port: 80
      targetPort: http