apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: gitea-secrets
  namespace: default
  labels:
    app: gitea
spec:
  secretName: gitea-secrets
  organizationId: "9f7b77c1-18f7-4dc8-b252-b274015d6c40"
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: "35eb5259-b6a6-44dd-ae85-b3d90162fca6"
      secretKeyName: GITEA_DB_PASSWORD
    - bwSecretId: "eecce2cf-3d1a-4ebb-9e8f-b3d9016354d4"
      secretKeyName: GITEA_SECRET_KEY
    - bwSecretId: "e01bf370-8cc6-45b9-917f-b3d90163717c"
      secretKeyName: GITEA_INTERNAL_TOKEN
    - bwSecretId: "7f6f7c8a-5f3f-4c7d-9b77-b3d901638d03"
      secretKeyName: GITEA_LFS_JWT_SECRET
