apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: gitea-secrets
  namespace: default
  labels:
    app: gitea
spec:
  secretName: gitea-secrets
  organizationId: "9f7b77c1-18f7-4dc8-b252-b274015d6c40"
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: "REPLACE_WITH_BW_SECRET_ID"
      secretKeyName: GITEA_DB_PASSWORD
    - bwSecretId: "REPLACE_WITH_BW_SECRET_ID"
      secretKeyName: GITEA_SECRET_KEY
    - bwSecretId: "REPLACE_WITH_BW_SECRET_ID"
      secretKeyName: GITEA_INTERNAL_TOKEN
