apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: default
  labels:
    app: gitea
data:
  USER_UID: "1000"
  USER_GID: "1000"
  
  # Database Configuration
  GITEA__database__DB_TYPE: postgres
  GITEA__database__HOST: gitea-postgres-service:5432
  GITEA__database__NAME: gitea
  GITEA__database__USER: gitea
  GITEA__database__SSL_MODE: disable
  
  # Server Configuration
  GITEA__server__DOMAIN: gitea.torquasmvo.com
  GITEA__server__ROOT_URL: https://gitea.torquasmvo.com/
  GITEA__server__HTTP_PORT: "3000"
  
  # SSH Configuration
  GITEA__server__START_SSH_SERVER: "true"
  GITEA__server__SSH_DOMAIN: gitea-ssh.torquasmvo.com
  GITEA__server__SSH_PORT: "2222"        # External port (Router/URL)
  GITEA__server__SSH_LISTEN_PORT: "2222" # Internal container port
  
  # Service Configuration
  GITEA__service__DISABLE_REGISTRATION: "true"
  GITEA__service__SHOW_REGISTRATION_BUTTON: "false"
  GITEA__repository__DEFAULT_BRANCH: "master"
  GITEA__repository__PREFERRED_LICENSES: "MIT"
