apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitwarden-secrets.yaml
  - configmap.yaml
  - gitea-pvc.yaml
  - gitea-postgres-pvc.yaml
  - gitea-postgres-deploy.yaml
  - deploy.yaml
  - svc.yaml
  - ingressroute.yaml
