[env]
KUBECONFIG = "{{env.HOME}}/.kube/config"
TALOSCONFIG = "{{env.HOME}}/.talos/talosconfig"
SOPS_AGE_KEY_FILE = "{{env.HOME}}/.config/sops/age/keys.txt"

[tools]
"aqua:kubernetes/kubectl" = "v1.34.2"
"aqua:kubernetes-sigs/kustomize" = "kustomize/v5.8.0"
"aqua:helm/helm" = "v4.0.1"
"aqua:budimanjojo/talhelper" = "v3.0.41"
"aqua:siderolabs/talos" = "v1.11.5"
"aqua:derailed/k9s" = "v0.50.16"
"aqua:yannh/kubeconform" = "v0.7.0"
"aqua:getsops/sops" = "v3.11.0"
"aqua:FiloSottile/age" = "v1.2.1"
