[env]
KUBECONFIG = "{{env.HOME}}/.kube/config"
TALOSCONFIG = "{{env.HOME}}/.talos/talosconfig"
SOPS_AGE_KEY_FILE = "{{env.HOME}}/.config/sops/age/keys.txt"

[tools]
"aqua:kubernetes/kubectl" = "v1.35.1"
"aqua:kubernetes-sigs/kustomize" = "kustomize/v5.8.0"
"aqua:helm/helm" = "v4.1.1"
"aqua:budimanjojo/talhelper" = "v3.1.5"
"aqua:siderolabs/talos" = "v1.12.4"
"aqua:derailed/k9s" = "v0.50.18"
"aqua:yannh/kubeconform" = "v0.7.0"
"aqua:getsops/sops" = "v3.12.1"
"aqua:FiloSottile/age" = "v1.3.1"
"aqua:argoproj/argo-cd" = "v3.3.2"
"aqua:cli/cli" = "v2.87.2"
