[env]
KUBECONFIG = "{{env.HOME}}/.kube/config"
TALOSCONFIG = "{{env.HOME}}/.talos/config"
SOPS_AGE_KEY_FILE = "{{env.HOME}}/.config/sops/age/keys.txt"

[tools]
"aqua:kubernetes/kubectl" = "v1.34.1"
"aqua:kubernetes-sigs/kustomize" = "kustomize/v5.8.0"
"aqua:helm/helm" = "v3.19.2"
"aqua:budimanjojo/talhelper" = "v3.0.39"
"aqua:siderolabs/talos" = "v1.11.3"
"aqua:yannh/kubeconform" = "v0.6.7"
"aqua:getsops/sops" = "v3.11.0"
"aqua:FiloSottile/age" = "v1.2.1"
