# --- SERVICE ---
---
apiVersion: v1
kind: Service
metadata:
  name: mylar3
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mylar3.torquasmvo.internal
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.229
  selector:
    app: mylar3
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
