apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-pdf-config-pvc-lh
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-prod
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-pdf-logs-pvc-lh
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-prod
  volumeMode: Filesystem
