apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-label-remover
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-label-remover
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-label-remover
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-label-remover
subjects:
  - kind: ServiceAccount
    name: node-label-remover
    namespace: kube-system
