# # kubernetes/infrastructure/longhorn/nodes/longhorn-node-config.yaml
# apiVersion: v1
# kind: Node
# metadata:
#   name: cyborg
#   labels:
#     node.longhorn.io/create-default-disk: "config"
#   annotations:
#     node.longhorn.io/default-disks-config: >-
#       [
#         {
#           "name": "disk-1",
#           "path": "/mnt/longhorn-storage",
#           "allowScheduling": true,
#           "storageReserved": 199715979264,
#           "tags": ["usb-ssd","temp-disk"]
#         }
#       ]
# ---
# apiVersion: v1
# kind: Node
# metadata:
#   name: kube2
#   labels:
#     node.longhorn.io/create-default-disk: "config"
#   annotations:
#     node.longhorn.io/default-disks-config: >-
#       [
#         {
#           "name": "disk-1",
#           "path": "/mnt/longhorn-storage",
#           "allowScheduling": true,
#           "storageReserved": 214748364800,
#           "tags": ["nvme"]
#         }
#       ]
# ---
# apiVersion: v1
# kind: Node
# metadata:
#   name: brainiac
#   labels:
#     node.longhorn.io/create-default-disk: "config"
#   annotations:
#     node.longhorn.io/default-disks-config: >-
#       [
#         {
#           "name": "disk-1",
#           "path": "/mnt/longhorn-storage",
#           "allowScheduling": true,
#           "storageReserved": 214748364800,
#           "tags": ["ssd"]
#         }
#       ]
---
apiVersion: v1
kind: Node
metadata:
  name: brainiac-00
  labels:
    node.longhorn.io/create-default-disk: "config"
  annotations:
    node.longhorn.io/default-disks-config: >-
      [
        {
          "name": "disk-1",
          "path": "/var/mnt/longhorn",
          "allowScheduling": true,
          "storageReserved": 30Gi,
          "tags": ["nvme"]
        }
      ]
---
apiVersion: v1
kind: Node
metadata:
  name: brainiac-01
  labels:
    node.longhorn.io/create-default-disk: "config"
  annotations:
    node.longhorn.io/default-disks-config: >-
      [
        {
          "name": "disk-1",
          "path": "/var/mnt/longhorn",
          "allowScheduling": true,
          "storageReserved": 30Gi,
          "tags": ["nvme"]
        }
      ]
