apiVersion: v1
kind: Service
metadata:
  name: transmission
  annotations:
    external-dns.alpha.kubernetes.io/hostname: transmission.torquasmvo.internal
spec:
  selector:
    app: transmission
  type: LoadBalancer
  loadBalancerIP: 10.0.0.202
  ports:
    - name: web-ui
      port: 9091
      targetPort: web
      protocol: TCP
    - name: peer-tcp
      port: 51413
      targetPort: peer-tcp
      protocol: TCP
    - name: peer-udp
      port: 51413
      targetPort: peer-udp
      protocol: UDP
