apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-survival
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: minecraft-survival
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minecraft-survival
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:2026.1.1
          ports:
            - containerPort: 25565
              protocol: TCP
            - containerPort: 25565
              protocol: UDP
            - containerPort: 19132
              protocol: UDP
          env:
            - name: TZ
              value: "America/New_York"
            - name: EULA
              value: "TRUE"
            - name: ONLINE_MODE
              value: "false"
            - name: VERSION
              value: "1.21.5"
            - name: TYPE
              value: "FABRIC"
            - name: MEMORY
              value: "4G"
            - name: ENABLE_ROLLING_LOGS
              value: "FALSE"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft-survival-data-longhorn
