# kubernetes/apps/default/tautulli/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: tautulli
  namespace: default
  labels:
    app: tautulli
  annotations:
    external-dns.alpha.kubernetes.io/hostname: tautulli.torquasmvo.internal
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.207
  selector:
    app: tautulli
  ports:
    - name: http
      port: 8181
      targetPort: 8181
