# kubernetes/apps/default/radarr/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: default
  labels:
    app: radarr
  annotations:
    external-dns.alpha.kubernetes.io/hostname: radarr.torquasmvo.internal
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.225
  selector:
    app: radarr
  ports:
    - name: http
      port: 7878
      targetPort: 7878
