# --- SERVICE ---
---
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: jellyseerr.torquasmvo.internal
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.219
  selector:
    app: jellyseerr
  ports:
    - name: http
      protocol: TCP
      port: 5055
      targetPort: 5055
