apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tuppr-longhorn-reader
rules:
  - apiGroups: ["longhorn.io"]
    resources: ["volumes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tuppr-longhorn-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tuppr-longhorn-reader
subjects:
  - kind: ServiceAccount
    name: tuppr
    namespace: system-upgrade
