apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-downloads-pv-default
spec:
  capacity:
    storage: 2Ti
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nfs:
    server: truenas1-nfs.torquasmvo.internal
    path: /mnt/fast/downloaders/sabnzbd/downloads
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - noatime
