apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-config
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-cache-pv
spec:
  capacity:
    storage: 2Ti
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  nfs:
    server: truenas-nfs.torquasmvo.internal
    path: /mnt/media/tdarr_temp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-cache
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 2Ti
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: tdarr-cache-pv
