apiVersion: v1
kind: Service
metadata:
  name: tdarr
  namespace: default
  labels:
    app: tdarr
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.210
  selector:
    app: tdarr
  ports:
    - name: http
      port: 8265
      targetPort: web
      protocol: TCP
    - name: server
      port: 8266
      targetPort: server
      protocol: TCP
    - name: node
      port: 8267
      targetPort: node
      protocol: TCP
