apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - metallb-ippool.yaml
  - bitwarden-secrets.yaml
  - pvc.yaml
  - deploy.yaml
  - svc-dns.yaml
  - svc-ui.yaml
