apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-dns-config
  namespace: dns-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-prod
  resources:
    requests:
      storage: 5Gi
