apiVersion: v1
kind: Service
metadata:
  name: technitium-dns-ui-lb
  namespace: dns-system
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.238
  selector:
    app: technitium-dns
  ports:
    - name: http
      port: 5380
      targetPort: 5380
      protocol: TCP
    - name: https
      port: 53443
      targetPort: 53443
      protocol: TCP
