apiVersion: v1
kind: Service
metadata:
  name: peanut
  namespace: default
  labels:
    app: peanut
  annotations:
    external-dns.alpha.kubernetes.io/hostname: peanut.torquasmvo.internal
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.206   # Pick a free IP from your MetalLB pool
  selector:
    app: peanut
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
