apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seerr
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`seerr.torquasmvo.com`)
      kind: Rule
      services:
        - name: seerr
          namespace: default
          port: 5055
    - match: Host(`jellyseerr.torquasmvo.com`)
      kind: Rule
      middlewares:
        - name: jellyseerr-to-seerr
      services:
        - name: seerr
          namespace: default
          port: 5055
  tls:
    secretName: traefik-dashboard-tls
