# --- SERVICE ---
---
apiVersion: v1
kind: Service
metadata:
  name: seerr
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: seerr.torquasmvo.internal
    metallb.universe.tf/loadBalancerIPs: 10.0.0.219
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.219
  selector:
    app: seerr
  ports:
    - name: http
      protocol: TCP
      port: 5055
      targetPort: 5055
