apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-config-pvc-lh
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-prod
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-data-pvc-lh
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn-prod
  volumeMode: Filesystem

