apiVersion: v1
kind: Service
metadata:
  name: opencloud
  namespace: default
  labels:
    app: opencloud
spec:
  type: ClusterIP
  selector:
    app: opencloud
  ports:
    - name: http
      port: 9200
      targetPort: http

