apiVersion: apps/v1
kind: Deployment
metadata:
  name: hytale
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: hytale
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hytale
    spec:
      containers:
        - name: hytale
          image: indifferentbroccoli/hytale-server-docker:v1.0.6
          ports:
            - containerPort: 5520
              protocol: UDP
          env:
            - name: TZ
              value: "America/New_York"
            - name: SERVER_NAME
              value: "BrainiacHytale"
            - name: DEFAULT_PORT
              value: "5520"
            - name: MAX_PLAYERS
              value: "20"
            - name: VIEW_DISTANCE
              value: "12"
            - name: ENABLE_BACKUPS
              value: "true"
            - name: BACKUP_FREQUENCY
              value: "30"
            - name: AUTH_MODE
              value: "authenticated"
            - name: ACCEPT_EARLY_PLUGINS
              value: "false"
            - name: DOWNLOAD_ON_START
              value: "true"
            - name: DISABLE_SENTRY
              value: "true"
            - name: USE_AOT_CACHE
              value: "true"
            - name: MAX_MEMORY
              value: "7G"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: data
              mountPath: /home/hytale/server-files
          resources:
            requests:
              memory: "4Gi"
              cpu: "2000m"
            limits:
              memory: "8Gi"
              cpu: "4000m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hytale-data
