apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hytale-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-prod
  resources:
    requests:
      storage: 20Gi
