apiVersion: v1
kind: Service
metadata:
  name: hytale
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hytale.torquasmvo.internal
spec:
  type: LoadBalancer
  loadBalancerIP: "10.0.0.220"
  ports:
    - name: hytale-udp
      port: 5520
      protocol: UDP
      targetPort: 5520
  selector:
    app.kubernetes.io/name: hytale
