apiVersion: apps/v1
kind: Deployment
metadata:
  name: nut-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: nut-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nut-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nut-exporter
    spec:
      containers:
      - name: nut-exporter
        image: druggeri/nut_exporter:3.2.3
        ports:
        - containerPort: 9199
          name: http
        env:
        - name: NUT_EXPORTER_SERVER
          value: "batterypi.torquasmvo.internal"
        - name: NUT_EXPORTER_SERVERPORT
          value: "3493"
        - name: NUT_EXPORTER_USERNAME
          value: "upsmon_remote"
        - name: NUT_EXPORTER_PASSWORD
          value: "hunter2"
        - name: NUT_EXPORTER_VARIABLES
          value: "battery.charge,battery.runtime,battery.voltage,battery.voltage.nominal,input.voltage,input.voltage.nominal,ups.load,ups.realpower.nominal,ups.status"
