apiVersion: apps/v1
kind: Deployment
metadata:
  name: nut-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: nut-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nut-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nut-exporter
    spec:
      containers:
      - name: nut-exporter
        image: druggeri/nut_exporter:3.1.1
        ports:
        - containerPort: 9199
          name: http
        env:
        - name: NUT_EXPORTER_VARIABLES
          value: "batterypi.torquasmvo.internal:3493"
