apiVersion: v1
kind: Service
metadata:
  name: nut-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: nut-exporter
spec:
  selector:
    app.kubernetes.io/name: nut-exporter
  ports:
  - name: http
    port: 9199
    targetPort: 9199
