apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-prod
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  dataLocality: "best-effort"
  recurringJobSelector: |
    [
      { "name": "prod", "isGroup": true }
    ]
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
