apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: external-dns-tsig
  namespace: dns-external
spec:
  secretName: external-dns-tsig
  organizationId: "9f7b77c1-18f7-4dc8-b252-b274015d6c40"
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: "2ca37c88-5af3-4715-a7e0-b3d601532f4a"
      secretKeyName: tsig-secret
