apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: semaphore-secrets
  namespace: default
  labels:
    app: semaphore
spec:
  secretName: semaphore-secrets
  organizationId: "9f7b77c1-18f7-4dc8-b252-b274015d6c40"
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: "998fede8-b230-4b8a-88c7-b35d01138318"
      secretKeyName: SEMAPHORE_ADMIN_PASSWORD
    - bwSecretId: "76d3d9dc-966b-4a70-8638-b34f00e5b811"
      secretKeyName: SEMAPHORE_DB_PASS
