apiVersion: apps/v1
kind: Deployment
metadata:
  name: semaphore-deployment
  labels:
    app: semaphore
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: semaphore
  template:
    metadata:
      labels:
        app: semaphore
    spec:
      serviceAccountName: semaphoreui-tailscale
      containers:
        - name: semaphore
          image: semaphoreui/semaphore:v2.17.8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: SEMAPHORE_DB_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: semaphore-configmap
                  key: SEMAPHORE_DB_DIALECT
            - name: SEMAPHORE_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: semaphore-configmap
                  key: SEMAPHORE_DB_HOST
            - name: SEMAPHORE_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: semaphore-configmap
                  key: SEMAPHORE_DB_PORT
            - name: SEMAPHORE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: semaphore-configmap
                  key: SEMAPHORE_DB_NAME
            - name: SEMAPHORE_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: semaphore-configmap
                  key: SEMAPHORE_DB_USER
            - name: SEMAPHORE_ADMIN_NAME
              valueFrom:
                configMapKeyRef:
                  name: semaphore-configmap
                  key: SEMAPHORE_ADMIN_NAME
            - name: SEMAPHORE_ADMIN_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: semaphore-configmap
                  key: SEMAPHORE_ADMIN_EMAIL
            - name: SEMAPHORE_DB_PATH
              valueFrom:
                configMapKeyRef:
                  name: semaphore-configmap
                  key: SEMAPHORE_DB_PATH
            - name: SEMAPHORE_CONFIG_PATH
              valueFrom:
                configMapKeyRef:
                  name: semaphore-configmap
                  key: SEMAPHORE_CONFIG_PATH
            - name: SEMAPHORE_TMP_PATH
              valueFrom:
                configMapKeyRef:
                  name: semaphore-configmap
                  key: SEMAPHORE_TMP_PATH
            - name: SEMAPHORE_DB_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: semaphore-configmap
                  key: SEMAPHORE_DB_OPTIONS
            - name: SEMAPHORE_ADMIN
              value: "admin"
            - name: SEMAPHORE_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: semaphore-secrets
                  key: SEMAPHORE_ADMIN_PASSWORD
            - name: SEMAPHORE_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: semaphore-secrets
                  key: SEMAPHORE_DB_PASS
            - name: SEMAPHORE_ACCESS_KEY_ENCRYPTION
              valueFrom:
                secretKeyRef:
                  name: semaphore-secrets
                  key: SEMAPHORE_ACCESS_KEY_ENCRYPTION
          volumeMounts:
            - name: semaphore-config-storage
              mountPath: /etc/semaphore
            - name: semaphore-static-storage
              mountPath: /tmp/semaphore
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
        - name: tailscale
          image: tailscale/tailscale:stable
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          env:
            - name: TS_USERSPACE
              value: "false"
            - name: TS_KUBE_SECRET
              value: "semaphoreui-tailscale-state"
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale
                  key: TS_AUTHKEY
            - name: TS_EXTRA_ARGS
              value: "--hostname=semaphoreui-sidecar --accept-routes=true"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          volumeMounts:
            - mountPath: /dev/net/tun
              name: dev-net-tun
            - mountPath: /var/lib/tailscale
              name: tailscale-state
      volumes:
        - name: semaphore-config-storage
          persistentVolumeClaim:
            claimName: semaphore-config-pvc-lh
        - name: semaphore-static-storage
          persistentVolumeClaim:
            claimName: semaphore-static-pvc-lh
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: tailscale-state
          emptyDir: {}
      securityContext:
        fsGroup: 1001
      restartPolicy: Always
