# kubernetes/apps/default/semaphoreui/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tailscale-rbac.yaml
  - deploy.yaml
  - svc.yaml
  - pvc.yaml
  - configmap.yaml
  - bitwarden-secrets.yaml
  - semaphore-postgres-pvc.yaml
  - semaphore-postgres-deploy.yaml
