# kubernetes/apps/default/semaphoreui/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitwarden-secrets.yaml
  - pvc.yaml
helmCharts:
  - name: semaphore
    repo: https://semaphoreui.github.io/charts
    version: 16.0.6
    releaseName: semaphoreui
    namespace: default
    valuesFile: values.yaml
