apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-lh
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-prod
  resources:
    requests:
      storage: 5Gi
