apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-config-pvc-lh
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-prod
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-static-pvc-lh
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-prod
  resources:
    requests:
      storage: 1Gi
