apiVersion: v1
kind: Service
metadata:
  name: semaphore-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: semaphore-service.torquasmvo.internal
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.221
  selector:
    app: semaphore # This must match the 'app' label in your Deployment's Pod template
  ports:
    - protocol: TCP
      port: 3000      # The port on the Service (internal to the cluster)
      targetPort: 3000 # The port your container (Semaphore) is listening on
