apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jdownloader-config-pvc-lh
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-prod
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jdownloader-output-pv
spec:
  capacity:
    storage: 100Gi # Adjust based on your expected storage needs
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # Use "" for static provisioning without a StorageClass
  nfs:
    server: truenas1-nfs.torquasmvo.internal
    path: /mnt/fast/downloaders/jdownloader
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jdownloader-output-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi # This should match or be less than the PV capacity
  storageClassName: "" # Important: This must match the PV's storageClassName