apiVersion: v1
kind: Service
metadata:
  name: jdownloader-service
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.233
  selector:
    app: jdownloader # This must match the 'app' label in your Deployment's Pod template
  ports:
    - protocol: TCP
      port: 5800      # The port on the Service (internal to the cluster)
      targetPort: 5800 # The port your container (JDownloader) is listening on
