apiVersion: apps/v1
kind: Deployment
metadata:
  name: vert
  namespace: default
  labels:
    app: vert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vert
  template:
    metadata:
      labels:
        app: vert
    spec:
      containers:
        - name: vert
          image: ghcr.io/vert-sh/vert:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
