apiVersion: v1
kind: Service
metadata:
  name: vert
  namespace: default
  labels:
    app: vert
spec:
  type: ClusterIP
  selector:
    app: vert
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
