apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-survival
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: minecraft-survival
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minecraft-survival
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:2025.12.0
          ports:
            - containerPort: 25565
              protocol: TCP
            - containerPort: 25565
              protocol: UDP
            - containerPort: 19132
              protocol: UDP
          env:
            - name: TZ
              value: "America/New_York"
            - name: EULA
              value: "TRUE"
            - name: ONLINE_MODE
              value: "false"
            - name: VERSION
              value: "1.21.5"
            - name: TYPE
              value: "FABRIC"
            - name: MEMORY
              value: "4G"
            - name: ENABLE_ROLLING_LOGS
              value: "TRUE"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft-survival-data-longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-creative
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: minecraft-creative
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minecraft-creative
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:2025.12.0
          ports:
            - containerPort: 25565
              protocol: TCP
            - containerPort: 25565
              protocol: UDP
          env:
            - name: TZ
              value: "America/New_York"
            - name: EULA
              value: "TRUE"
            - name: ONLINE_MODE
              value: "TRUE"
            - name: VERSION
              value: "1.21.5"
            - name: TYPE
              value: "FABRIC"
            - name: MODE
              value: "creative"
            - name: SERVER_NAME
              value: "Raven"
            - name: ENABLE_COMMAND_BLOCK
              value: "TRUE"
            - name: ENABLE_RCON
              value: "TRUE"
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minecraft-secrets
                  key: RCON_PASSWORD
            - name: ENABLE_ROLLING_LOGS
              value: "TRUE"
            - name: MEMORY
              value: "4G"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft-creative-data-longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-fox
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: minecraft-fox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minecraft-fox
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:2025.12.0
          ports:
            - containerPort: 25565
              protocol: TCP
            - containerPort: 25565
              protocol: UDP
          env:
            - name: TZ
              value: "America/New_York"
            - name: EULA
              value: "TRUE"
            - name: ONLINE_MODE
              value: "TRUE"
            - name: VERSION
              value: "1.21.1"
            - name: TYPE
              value: "NEOFORGE"
            - name: MODE
              value: "creative"
            - name: SERVER_NAME
              value: "Fox"
            - name: ENABLE_RCON
              value: "TRUE"
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minecraft-secrets
                  key: RCON_PASSWORD
            - name: MODS
              value: >-
                https://cdn.modrinth.com/data/VsM5EDoI/versions/YSWV62mG/blueprint-1.21.1-8.0.8.jar,
                https://cdn.modrinth.com/data/lhGA9TYQ/versions/ZxYGwlk0/architectury-13.0.8-neoforge.jar,
                https://cdn.modrinth.com/data/R2OftAxM/versions/opCbq7uB/FarmersDelight-1.21.1-1.2.9.jar,
                https://cdn.modrinth.com/data/uXXizFIs/versions/CnpoQxCx/ferritecore-7.0.2-neoforge.jar,
                https://cdn.modrinth.com/data/U1ACi6eg/versions/rflSuXTL/furnitureexpanded-neoforge-1.2%2B1.21.1.jar,
                https://cdn.modrinth.com/data/gvQqBUqZ/versions/G5SDYehn/lithium-neoforge-0.15.1%2Bmc1.21.1.jar,
                https://cdn.modrinth.com/data/InYMuiQt/versions/RQ5qgaUC/neapolitan-1.21.1-6.0.1.jar,
                https://cdn.modrinth.com/data/nmDcB62a/versions/8Be8uJW6/modernfix-neoforge-5.25.1%2Bmc1.21.1.jar
            - name: ENABLE_ROLLING_LOGS
              value: "TRUE"
            - name: MEMORY
              value: "4G"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft-fox-data-longhorn
