---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-survival
spec:
  type: LoadBalancer
  loadBalancerIP: "10.0.0.211" # Add this line
  ports:
    - name: survival-tcp
      port: 25565
      protocol: TCP
      targetPort: 25565
    - name: survival-udp
      port: 25565
      protocol: UDP
      targetPort: 25565
    - name: bedrock-udp
      port: 19132
      protocol: UDP
      targetPort: 19132
  selector:
    app.kubernetes.io/name: minecraft-survival
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-creative
spec:
  type: LoadBalancer
  loadBalancerIP: "10.0.0.212" # Add this line
  ports:
    - name: creative-tcp
      port: 25565
      protocol: TCP
      targetPort: 25565
    - name: creative-udp
      port: 25565
      protocol: UDP
      targetPort: 25565
  selector:
    app.kubernetes.io/name: minecraft-creative
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-fox
spec:
  type: LoadBalancer
  loadBalancerIP: "10.0.0.213" # Add this line
  ports:
    - name: fox-tcp
      port: 25565
      protocol: TCP
      targetPort: 25565
    - name: fox-udp
      port: 25565
      protocol: UDP
      targetPort: 25565
  selector:
    app.kubernetes.io/name: minecraft-fox
