# svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: romm-svc
  labels:
    app.kubernetes.io/name: romm
    app.kubernetes.io/instance: romm
  annotations:
    external-dns.alpha.kubernetes.io/hostname: romm.torquasmvo.internal
spec:
  selector:
    app.kubernetes.io/name: romm
    app.kubernetes.io/component: web
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 8080 # Container port
  type: LoadBalancer # Exposes the app outside the cluster.
  loadBalancerIP: 10.0.0.216