# Replace placeholder Bitwarden IDs with real values before syncing.
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: jellystat-secrets
  namespace: default
  labels:
    app: jellystat
spec:
  secretName: jellystat-secrets
  organizationId: "9f7b77c1-18f7-4dc8-b252-b274015d6c40" # Same as others
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: "c9076412-8d61-4476-b844-b3fb010c7951"
      secretKeyName: JELLYSTAT_POSTGRES_PASSWORD
    - bwSecretId: "13f5589a-daa6-4906-a703-b3fb010bfcc5"
      secretKeyName: JELLYSTAT_JWT_SECRET
