apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellystat-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-prod
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellystat-postgres-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-prod
