---
# --- DEPLOYMENT ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: komga
  namespace: default
  labels:
    app: komga
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: komga
  template:
    metadata:
      labels:
        app: komga
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: komga
          image: gotson/komga:1.23.6
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "America/New_York"
          ports:
            - containerPort: 25600
          volumeMounts:
            - name: komga-config
              mountPath: /config
            - name: komga-comics
              mountPath: /data
      volumes:
        - name: komga-config
          persistentVolumeClaim:
            claimName: komga-config-lh
        - name: komga-comics
          persistentVolumeClaim:
            claimName: media-comics-pvc
