---
# --- SERVICE (MetalLB) ---
apiVersion: v1
kind: Service
metadata:
  name: komga
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: komga.torquasmvo.internal
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.205
  selector:
    app: komga
  ports:
    - name: http
      protocol: TCP
      port: 25600
      targetPort: 25600
