apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-vpn-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-prod
  resources:
    requests:
      storage: 1Gi
---
